Fix error TS2345 in Bar component with passing varargs to view
This shit:

    lib/components/Bar.ts(24,33): error TS2345: Argument of type 'VNode[]' is not assignable to parameter of type 'VNode'.
      Property 'sel' is missing in type 'VNode[]'.

Which I can reduce to this:

    const foo = (...trees: string[]) => `
        <div>
            ${trees}
        </div>
    `;

    const bar = (...trees: string[]) => `
        <div>
            ${foo(trees)}
        </div>
    `;

Seems to not work anymore. ¯\_(ツ)_/¯